-- 마스터 데이터 생성 (프론트엔드 요구사항 반영)

-- Category 데이터 (POPUP 타입)
INSERT INTO category (name, type, created_at, updated_at)
VALUES 
    ('패션', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('뷰티', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('음식', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('건강', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('공연/전시', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('스포츠', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('키즈', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('아트', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('굿즈', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('반려동물', 'POPUP', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6))
ON CONFLICT (type, name) DO NOTHING;

-- Category 데이터 (CONSUMER 타입 - 소비자 관심사)
INSERT INTO category (name, type, created_at, updated_at)
VALUES 
    ('패션', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('뷰티', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('음식', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('건강', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('공연/전시', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('스포츠', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('키즈', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('아트', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('굿즈', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('반려동물', 'CONSUMER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6))
ON CONFLICT (type, name) DO NOTHING;

-- Style 데이터 (팝업 분위기)
INSERT INTO style (name, created_at, updated_at)
VALUES 
    ('혼자여도 좋은', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('가족과 함께', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('친구와 함께', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('연인과 함께', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('반려동물과 함께', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('아기자기한', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('감성적인', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('활기찬', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('차분한', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('체험하기 좋은', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('포토존', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('레트로/빈티지', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('체험가능', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('실내', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('야외', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6))
ON CONFLICT (name) DO NOTHING;

-- Feature 데이터 (편의사항)
INSERT INTO feature (name, created_at, updated_at)
VALUES 
    ('무료주차', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('무료입장', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('예약가능', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('굿즈판매', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('와이파이', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('휠체어 접근 가능', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('애견 동반', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6))
ON CONFLICT (name) DO NOTHING;

